pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/Raghukongala/jenkins-repo.git', branch: 'main'
            }
        }

        stage('Build') {
            steps {
                dir('SpringBootJspAPI/SpringBootJspApp/SpringBootJspAPI/SpringBootJspAPI/SpringBootJspApp') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Test') {
            steps {
                dir('SpringBootJspAPI/SpringBootJspApp/SpringBootJspAPI/SpringBootJspAPI/SpringBootJspApp') {
                    sh 'mvn test'
                }
            }
        }

        stage('Deploy') {
            steps {
                dir('SpringBootJspAPI/SpringBootJspApp/SpringBootJspAPI/SpringBootJspAPI/SpringBootJspApp') {
                    sh 'echo "Deploying application..."'
                }
            }
        }
    }
}
